apiVersion: apps/v1
kind: Deployment
metadata:
  name: erp-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: erp-backend
  template:
    metadata:
      labels:
        app: erp-backend
    spec:
      containers:
      - name: erp-backend
        image: afaqzaman/erp-backend:latest
        ports:
        - containerPort: 5000
        env:
        - name: DB_HOST
          value: "mysql-service"
        - name: DB_USER
          value: "root"
        - name: DB_PASSWORD
          value: "admin123"
        - name: DB_NAME
          value: "devops_erp"
        - name: JWT_SECRET
          value: "secret123"
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: erp-backend
  ports:
  - port: 5000
    targetPort: 5000
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: erp-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: erp-frontend
  template:
    metadata:
      labels:
        app: erp-frontend
    spec:
      containers:
      - name: erp-frontend
        image: afaqzaman/erp-frontend:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
    app: erp-frontend
  ports:
  - port: 3000
    targetPort: 80
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql:8.0
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "admin123"
        - name: MYSQL_DATABASE
          value: "devops_erp"
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-service
spec:
  selector:
    app: mysql
  ports:
  - port: 3306
    targetPort: 3306
  type: ClusterIP